Incr17
tim3-p/go-link-shortener pull request #18
Opened 2022-06-01 18:42 UTC by tim3-p

2022-06-05 23:04 UTC, Barugoo requested changes
Не вижу бенчмарков в коде, как идея: можно сделать две реализации хранилки метрик на сервере - через массив/линкед-лист и через мапку и сравнить их производительность в бенчмарках на разных операциях. Бенчмарки и разницу профилей сохранить

Не хватает примеров использования эндпоинтов, а так же комментариев к многим экспортируемым сущностям

2022-06-13 11:12 UTC, rktkov approved these changes

2022-06-13 11:12 UTC, rktkov commented on internal/storage/map.go
> +// Get URLs by user ID from map storage
Согласно рекомендациям по именованию - первым словом должно быть имя метода, такое как задано в коде.

2022-06-13 11:12 UTC, rktkov commented on internal/storage/file.go
> +// File base descriptor
Тот же комментарий - первым должно быть имя структуры как в коде.

2022-06-25 08:55 UTC, merged